### ISSUE TITLE
Bug 有亿点多

### ISSUE THREAD

**Issue by mcxiaolan** [zzy-ac/txt2epub#6]
浅浅在 Termux 体验了一把，其他系统没尝试过。

到装 Python 依赖很慢，开代理之后 cf 又 Just a moment，后面想了个办法，快到装 Python 依赖才开代理。

直接用 `txt2epub` 指令不行，进入目录执行 `python3 run.py` 才行（可能是安装脚本哪一步没有装好？网络问题？）

转完之后返回 ebooks 目录一看，好好好，txt 和转好的文件全没了，后面我有尝试注释掉一些 run.py 后面的删除文件部分，ls 了一下 `txt2epub` 发现 txt 在这里，电子书格式没看见，不知道是不是因为我用了Python3？

我不太会写这种东西，我也尝试过 calibre 正则表达式转，但是没有段首缩进两格，看起来就特别像是居左对齐。
easypub 默认的 css 不是很好看，章节标题总是有一层灰灰的，我也不太会写，所以找到了这里😊

作者看到后能不能抽点时间尝试修一修😞
说的不够详细请谅解，我还没学过Python awa

**Comment by zzy-ac** [comment]
你的操作流程讲述的有点模糊，请提供完整的日志，或提供可复现的具体流程。

termux无法安装依赖的事情你可以先给python换源，我程序就是用py3写的

**Comment by zzy-ac** [comment]
你说的txt2epub无法直接运行和文件不能成功复制出去等应该都是你安装脚本没有完全运行成功的原因

**Comment by mcxiaolan** [comment]
> 你说的txt2epub无法直接运行和文件不能成功复制出去等应该都是你安装脚本没有完全运行成功的原因

我也不知道该怎么办咯，我的 Termux 有一些比较重要的环境，所以说我不能清除数据重新装awa

**Comment by zzy-ac** [comment]
python换源，删掉txt2epub目录，然后重新运行一下脚本试试
