### ISSUE TITLE
send to kindle error

### ISSUE THREAD

**Issue by KysonGeek** [zzy-ac/txt2epub#7]
大家有没有遇到转出来的epub用邮箱发给kindle时，提示失败
<img width="596" alt="image" src="https://github.com/zzy-ac/txt2epub/assets/33253696/ec62a868-a33c-489f-999b-623ec352b00d">

**Comment by zzy-ac** [comment]
那就不要直接把epub发给kindle啊，不是可以生成azw3吗？

**Comment by KysonGeek** [comment]
现在kiindle不支持azw3了，txt太大了，直接上传kindle打不开。我分割了一下txt，然后转epub再上传kindle就成功了，可能是kindle有什么限制
<img width="1019" alt="image" src="https://github.com/zzy-ac/txt2epub/assets/33253696/7bf2ee80-42e3-4531-bb3d-b02eb192bea3">

**Comment by zzy-ac** [comment]
不清楚，不用kindle的，你可以自行了解，或者自行修改脚本生成mobi发过去。

**Comment by zzy-ac** [comment]
不清楚，不用kindle的，你可以自行了解，或者自行修改脚本生成mobi发过去。
